"""
Module to hold global configurations for the Swedish Chef.
Some of these are marked as to be changed by hand, while some
are marked to be changed programmatically. Please pay attention.
"""

# The directory wherein we can find the data for the chef
# @programmatic/manual - can be overwritten by user, but default is manually set
DATA_DIRECTORY = "tmp"





# RNN checkpoint directory
# @manual
CHECKPOINT_DIR = DATA_DIRECTORY + "/" + "rnn_checkpoints"

# Clusters directory where each kmeans cluster is stored
# @manual
CLUSTERS = DATA_DIRECTORY + "/" + "clusters/"

# The dataframe
# @manual
DATA_FRAME = DATA_DIRECTORY + "/" + "dataframe"

# The embeddings of all words in the recipes
# @manual: Generated by the word2vec_basic.py script
EMBEDDINGS_PATH = DATA_DIRECTORY + "/" + "embeddings"

# The path to the saved IngredientsTable object
# @programmatic
INGREDIENT_TABLE_PATH = DATA_DIRECTORY + "/" + "ingredient_table"

# The path to the saved kmeans object
# @programmatic
KMEANS_MODEL_PATH = DATA_DIRECTORY + "/" + "kmeans.model"

# The master directory where we store data
# @programmatic
MASTER_DATA_DIRECTORY = None

# The path to the dense matrix
# @manual
MATRIX = DATA_DIRECTORY + "/" + "matrix"

# The path to the sparse data matrix
# @manual
MATRIX_SPARSE = DATA_DIRECTORY + "/" + "sparsematrix"

# The new cookbook marker
# @manual
NEW_COOKBOOK_LINE = "NEW_COOKBOOK______________________________LINE"

# The new recipe marker
# @manual
NEW_RECIPE_LINE = "NEW_RECIPE__________________________________LINE"

# The name of the file that will contain all of the recipes in human
# readable format.
# @manual
RECIPE_FILE_NAME = "all_of_the_recipes.txt"

# The path to the recipe file
# @programmatic
RECIPE_FILE_PATH = DATA_DIRECTORY + "/" + RECIPE_FILE_NAME

# The path to the recipe file with ingredients replaced with single word versions
# @programmatic
RECIPE_FILE_SINGLE_PATH = DATA_DIRECTORY + "/" + "single_" + RECIPE_FILE_NAME

# The path to the recipe table
# @manual
RECIPE_TABLE_PATH = DATA_DIRECTORY + "/" + "recipe_table"

# The directory that the RNN data lives in
# @manual
RNN_DATA_DIR = DATA_DIRECTORY + "/" + "rnn_data"

# The similarity score average for the population of recipes
# @manual : Get it from the computer and then hand write it
SIM_MEAN = 0.118617649461

# The standard deviation for the population of recipes' similarity scores
# @manual: Get it from the computer and then hand write it
SIM_STAND_DEV = 0.06918336224729744

# The path to the training data for the RNN
# @manual
TRAINING_PATH = DATA_DIRECTORY + "/" + "rnn_training_data"

# The unique.txt ingredient file path
# @programmatic/manual - will overwrite with user input
UNIQUE = DATA_DIRECTORY + "/" + "unique.txt"

# The unique_within.txt ingredient file path
# @programmatic/manual - will overwrite with user input
UNIQUE_WITHIN = DATA_DIRECTORY + "/" + "unique_within.txt"

# The unit test banner to print around a unit test start and ending
# @manual
UNIT_TEST_HEADER = "============================================="

# Whether debug output should be printed as the program executes
# @programmatic
VERBOSE = False

# The path to the word2vec model
# @manual
WORD2VEC_MODEL_PATH = DATA_DIRECTORY + "/" + "word2vec.model"
